name: foursouls
services:
  # This config is for MongoDB v5+
  # It's a Replica Set (required for Prisma Client)
  mongo6:
    container_name: mongodb
    build:
      context: ./mongodb_replica
      args:
        MONGO_VERSION: 6
    environment:
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: password
      # MONGO_INITDB_DATABASE: ${DB_NAME}
      MONGO_REPLICA_HOST: localhost
      MONGO_REPLICA_PORT: 27017
      # Use "mongo" instead of "mongosh" before v5.0
      MONGO_COMMAND: 'mongosh'
    ports:
      - '27017:27017'
    restart: unless-stopped


    
    