package org.camposmdev.model.card.attribute;

public enum EntityTarget {
    UNDEFINED,
    ACTIVE_PLAYER,
    ACTIVE_PLAYER_THEN_CHOOSE_MONSTER_AND_PLAYER,
    ALL_MONSTERS,
    ALL_OTHER_PLAYERS,
    ALL_PLAYERS,
    ATTACKING_PLAYER,
    CHOOSE_LIVING_PLAYER,
    CHOOSE_MONSTER,
    CHOOSE_PLAYER,
    CHOOSE_PLAYER_AND_MONSTER,
    CHOOSE_PLAYER_OR_MONSTER,
    DIVIDE_TO_PLAYERS_OR_MONSTERS,
    LEFT_AND_RIGHT_PLAYER,
    LEFT_PLAYER,
    NON_ACTIVE_PLAYER,
    RANDOM_NON_ACTIVE_PLAYER,
    RANDOM_PLAYER,
    RIGHT_PLAYER,
    SOURCE_MONSTER,
    SOURCE_PLAYER,
    CHOOSE_THREE_PLAYERS
}
