package org.camposmdev.model.card.attribute.monster;

public enum ChallengeType {
    RESURRECTION_DAY,
    RESURRECTED_RAG_MAN,
    DEVOUT_MOM,
    GREEDS_GAMBLE,
    AVARICIOUS_GREED,
    MASQUERADE,
    ANONYMOUS_MASK_OF_INFAMY,
    DELIRIOUS,
    LORD_OF_THE_FLIES,
    SWARMING_THE_DUKE_OF_FLIES,
    TRICK,
    MISCHEVIOUS_THE_HAUNT,
    FATTYS_FEAST,
    HOW_THE_KRAMPUS_STOLE_CHRISTMAS,
    PILFERING_KRAMPUS,
    LIVE_LAUGH_LUST,
    LASCIVIOUS_LUST,
    DAY_OF_THE_DOODLER,
    THE_DOODLER,
    BLACK_CANVAS,
    STOMPING_GROUND,
    MARUADING_DADDY_LONG_LEGS
}
